### model
model_name_or_path: Meta-Llama-3-8B-Instruct
adapter_name_or_path: /mnt/sda/llmfact/LLaMA-Factory/spa_exp/llama3-8b/sigmoid
trust_remote_code: true

### method
finetuning_type: lora

### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/llama3-8b/lora/eval_sigmoid

### eval
batch_size: 4
